[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
core_contract = "AhzB75bfztVnP2mnfTxdxtNrYmUy194XUxzYcJtzpWv5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
