[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
core_contract = "AhzB75bfztVnP2mnfTxdxtNrYmUy194XUxzYcJtzpWv5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=b774ff16-080c-4631-8f30-c4ace3a8e7c4"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
